version: '3.8'

services:
  db:
    image: bitnami/postgresql:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: backend
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/backend
      # Other environment variables
    ports:
      - "3333:3333"

volumes:
  db:
    driver: local
    